{
 "title": "Infinispan - General",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "cache_name",
    "label": "cache_name",
    "query": "metrics(vendor_cache_manager_default_cache_.*_statistics_number_of_entries_in_memory)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances (up)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_health_number_of_nodes",
     "legendFormat": "Instances (up)"
    }
   ]
  },
  {
   "title": "Off Memory heap Use for $instance (MB)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_.*_statistics_off_heap_memory_used\",instance=~\"$instance\"}/(1024*1024),\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_user_cache_statistics_off_heap_memory_used\")"
    }
   ]
  },
  {
   "title": "Approximate Entries in Memory for $instance",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_(.*)_statistics_approximate_entries_in_memory\",instance=~\"$instance\"},\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_(.*)_statistics_approximate_entries_in_memory{node}\")"
    }
   ]
  },
  {
   "title": "Put Operations in $instance",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_.*_statistics_stores\",instance=~\"$instance\"},\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_user_cache_statistics_stores\")"
    }
   ]
  },
  {
   "title": "Average Read Time in ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_.*_statistics_average_read_time_nanos\",instance=~\"$instance\"}/1000000,\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_user_cache_statistics_stores\")",
     "legendFormat": "{{cache}}-{{node}}"
    }
   ]
  },
  {
   "title": "Average Write Time in ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"vendor_cache_manager_default_cache_.*_statistics_average_write_time_nanos\",instance=~\"$instance\"}/1000000,\"cache_name\", \"$1\", \"__name__\", \"vendor_cache_manager_default_cache_user_cache_statistics_stores\")\n",
     "legendFormat": "{{cache}} - {{node}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Threading on $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_daemon_count{instance=~\"$instance\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "base_thread_count{instance=~\"$instance\"}",
     "legendFormat": "Thread Count"
    },
    {
     "expr": "base_thread_max_count{instance=~\"$instance\"}",
     "legendFormat": "Max Count"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global Memory on $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedNonHeap_bytes{instance=~\"$instance\"}",
     "legendFormat": "Non Heap used"
    },
    {
     "expr": "base_memory_usedHeap_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "Memory Pools on $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Code Heap non-nmethods"
    },
    {
     "expr": "vendor_memoryPool_CodeHeap_profiled_nmethods_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Code Heap profiled nmethods"
    },
    {
     "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Code Heap non-profiled nmethods"
    },
    {
     "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Compressed Class"
    },
    {
     "expr": "vendor_memoryPool_Metaspace_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Metaspace"
    },
    {
     "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Tenured"
    },
    {
     "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Survivor"
    },
    {
     "expr": "vendor_memoryPool_Eden_Space_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "Eden"
    }
   ]
  },
  {
   "title": "Garbage Collection on $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_total{instance=~\"$instance\"}[45s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}